### ISSUE TITLE
Better names for TransformSpecialNamed and TransformSpecial?

### ISSUE THREAD

**Issue by searler** [sangria-graphql/macro-visit#1]
These are not yet documented.
As far as I can determine; they are used to modify a field of a case class.
Each specifies the type of the target field and TransformSpecialNamed names the field when the type matches more than one field. 

Might I suggest that they be named something like TransformField and TransformFieldByName?

**Comment by OlegIlyenko** [comment]
I agree, "Special" is not very descriptive name :) But I afraid that `TransformField` would be a bit confusing as well.

The main use-case for a library is to take one trait, let's say `Ast`, and traverse all of it's known subtypes and their fields that are of exactly same type `Ast`. This is why `TransformSpecial` is "special" - at allows you to visit a field of any type and not only of `Ast` type. For example, in sangria I use it to remove `position` from all `AstNode`s and `position` is not subtype of an `AstNode`: 

https://github.com/sangria-graphql/sangria/blob/master/src/main/scala/sangria/ast/QueryAst.scala#L327-L333

Now that I think about it, "transform" part of the name is also a bit silly because it's not only about transformation :) What do you think about `VisitAnyField` and `VisitAnyFieldByName`? Also, would you like to make a PR for this change?
